name: Test and Submit

on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: install dependencies
        run: npm install

      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: decode testcase
        run: openssl enc -d -aes-256-cbc -salt -k aaaa -in ./problems/1.two-sum/test -out ./problems/1.two-sum/test.csv

      - name: build
        run: go build ./.github/cmd/1.two-sum/main.go

      - name: run
        run: ./main
