name: Test and Submit

on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: install dependencies
        run: npm install

      - name: run tests
        run: ./.github/bin/test.sh
